import { Outfit } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/themes-provider";
import { ClerkProvider } from "@clerk/nextjs";
import  Provider  from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Provider>
            {children}
          </Provider>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}